#!/bin/bash
blastdbcmd -db /home/montoliu/40sp/data_renamed/aacet.faa -dbtype prot -entry aacet_DMAAMFHJ_03256 -out /home/montoliu/40sp/mut_sequences/dnaQ/aacet.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/aacet.faa -dbtype prot -entry aacet_DMAAMFHJ_02130 -out /home/montoliu/40sp/mut_sequences/mutL/aacet.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/aacet.faa -dbtype prot -entry aacet_DMAAMFHJ_03375 -out /home/montoliu/40sp/mut_sequences/mutS/aacet.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/aacet.faa -dbtype prot -entry aacet_DMAAMFHJ_03046 -out /home/montoliu/40sp/mut_sequences/mutT/aacet.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/aacet.faa -dbtype prot -entry aacet_DMAAMFHJ_01352 -out /home/montoliu/40sp/mut_sequences/mutY/aacet.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/aacet.faa -dbtype prot -entry aacet_DMAAMFHJ_03383 -out /home/montoliu/40sp/mut_sequences/uvrD/aacet.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/abaum.faa -dbtype prot -entry abaum_DGLPADFO_01165 -out /home/montoliu/40sp/mut_sequences/dnaQ/abaum.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/abaum.faa -dbtype prot -entry abaum_DGLPADFO_02436 -out /home/montoliu/40sp/mut_sequences/mutL/abaum.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/abaum.faa -dbtype prot -entry abaum_DGLPADFO_01493 -out /home/montoliu/40sp/mut_sequences/mutS/abaum.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/abaum.faa -dbtype prot -entry abaum_DGLPADFO_02624 -out /home/montoliu/40sp/mut_sequences/mutT/abaum.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/abaum.faa -dbtype prot -entry abaum_DGLPADFO_03758 -out /home/montoliu/40sp/mut_sequences/mutY/abaum.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/abaum.faa -dbtype prot -entry abaum_DGLPADFO_00885 -out /home/montoliu/40sp/mut_sequences/uvrD/abaum.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/amari.faa -dbtype prot -entry amari_EHLHLONF_03673 -out /home/montoliu/40sp/mut_sequences/dnaQ/amari.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/amari.faa -dbtype prot -entry amari_EHLHLONF_00884 -out /home/montoliu/40sp/mut_sequences/mutH/amari.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/amari.faa -dbtype prot -entry amari_EHLHLONF_02775 -out /home/montoliu/40sp/mut_sequences/mutL/amari.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/amari.faa -dbtype prot -entry amari_EHLHLONF_03449 -out /home/montoliu/40sp/mut_sequences/mutS/amari.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/amari.faa -dbtype prot -entry amari_EHLHLONF_01404 -out /home/montoliu/40sp/mut_sequences/mutT/amari.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/amari.faa -dbtype prot -entry amari_EHLHLONF_00809 -out /home/montoliu/40sp/mut_sequences/mutY/amari.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/amari.faa -dbtype prot -entry amari_EHLHLONF_02410 -out /home/montoliu/40sp/mut_sequences/uvrD/amari.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/atume.faa -dbtype prot -entry atume_HDHPLDKG_02443 -out /home/montoliu/40sp/mut_sequences/dnaQ/atume.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/atume.faa -dbtype prot -entry atume_HDHPLDKG_00342 -out /home/montoliu/40sp/mut_sequences/mutL/atume.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/atume.faa -dbtype prot -entry atume_HDHPLDKG_00021 -out /home/montoliu/40sp/mut_sequences/mutS/atume.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/atume.faa -dbtype prot -entry atume_HDHPLDKG_03438 -out /home/montoliu/40sp/mut_sequences/mutT/atume.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/atume.faa -dbtype prot -entry atume_HDHPLDKG_00434 -out /home/montoliu/40sp/mut_sequences/mutY/atume.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/atume.faa -dbtype prot -entry atume_HDHPLDKG_01666 -out /home/montoliu/40sp/mut_sequences/uvrD/atume.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/avine.faa -dbtype prot -entry avine_ACOPACLB_02750 -out /home/montoliu/40sp/mut_sequences/dnaQ/avine.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/avine.faa -dbtype prot -entry avine_ACOPACLB_00696 -out /home/montoliu/40sp/mut_sequences/mutL/avine.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/avine.faa -dbtype prot -entry avine_ACOPACLB_03597 -out /home/montoliu/40sp/mut_sequences/mutS/avine.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/avine.faa -dbtype prot -entry avine_ACOPACLB_01224 -out /home/montoliu/40sp/mut_sequences/mutT/avine.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/avine.faa -dbtype prot -entry avine_ACOPACLB_00424 -out /home/montoliu/40sp/mut_sequences/mutY/avine.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/avine.faa -dbtype prot -entry avine_ACOPACLB_00050 -out /home/montoliu/40sp/mut_sequences/uvrD/avine.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/bburg.faa -dbtype prot -entry bburg_IPLIGLPG_00705 -out /home/montoliu/40sp/mut_sequences/mutL/bburg.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/bburg.faa -dbtype prot -entry bburg_IPLIGLPG_01295 -out /home/montoliu/40sp/mut_sequences/mutS/bburg.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/bburg.faa -dbtype prot -entry bburg_IPLIGLPG_01244 -out /home/montoliu/40sp/mut_sequences/mutY/bburg.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/bburg.faa -dbtype prot -entry bburg_IPLIGLPG_01102 -out /home/montoliu/40sp/mut_sequences/uvrD/bburg.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/bcepa.faa -dbtype prot -entry bcepa_ENHLDEGJ_01249 -out /home/montoliu/40sp/mut_sequences/dnaQ/bcepa.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/bcepa.faa -dbtype prot -entry bcepa_ENHLDEGJ_00718 -out /home/montoliu/40sp/mut_sequences/mutL/bcepa.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/bcepa.faa -dbtype prot -entry bcepa_ENHLDEGJ_02239 -out /home/montoliu/40sp/mut_sequences/mutS/bcepa.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/bcepa.faa -dbtype prot -entry bcepa_ENHLDEGJ_00508 -out /home/montoliu/40sp/mut_sequences/mutT/bcepa.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/bcepa.faa -dbtype prot -entry bcepa_ENHLDEGJ_03001 -out /home/montoliu/40sp/mut_sequences/mutY/bcepa.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/bcepa.faa -dbtype prot -entry bcepa_ENHLDEGJ_01437 -out /home/montoliu/40sp/mut_sequences/uvrD/bcepa.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/bthet.faa -dbtype prot -entry bthet_HIHEOMHD_04234 -out /home/montoliu/40sp/mut_sequences/dnaQ/bthet.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/bthet.faa -dbtype prot -entry bthet_HIHEOMHD_01779 -out /home/montoliu/40sp/mut_sequences/mutL/bthet.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/bthet.faa -dbtype prot -entry bthet_HIHEOMHD_01019 -out /home/montoliu/40sp/mut_sequences/mutS/bthet.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/bthet.faa -dbtype prot -entry bthet_HIHEOMHD_00699 -out /home/montoliu/40sp/mut_sequences/mutT/bthet.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/bthet.faa -dbtype prot -entry bthet_HIHEOMHD_04302 -out /home/montoliu/40sp/mut_sequences/mutY/bthet.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/bthet.faa -dbtype prot -entry bthet_HIHEOMHD_03416 -out /home/montoliu/40sp/mut_sequences/uvrD/bthet.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/cfreu.faa -dbtype prot -entry cfreu_IOIGCAAH_03811 -out /home/montoliu/40sp/mut_sequences/dnaQ/cfreu.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/cfreu.faa -dbtype prot -entry cfreu_IOIGCAAH_00892 -out /home/montoliu/40sp/mut_sequences/mutH/cfreu.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/cfreu.faa -dbtype prot -entry cfreu_IOIGCAAH_04222 -out /home/montoliu/40sp/mut_sequences/mutL/cfreu.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/cfreu.faa -dbtype prot -entry cfreu_IOIGCAAH_00984 -out /home/montoliu/40sp/mut_sequences/mutS/cfreu.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/cfreu.faa -dbtype prot -entry cfreu_IOIGCAAH_03922 -out /home/montoliu/40sp/mut_sequences/mutT/cfreu.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/cfreu.faa -dbtype prot -entry cfreu_IOIGCAAH_00781 -out /home/montoliu/40sp/mut_sequences/mutY/cfreu.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/cfreu.faa -dbtype prot -entry cfreu_IOIGCAAH_04605 -out /home/montoliu/40sp/mut_sequences/uvrD/cfreu.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/cjeju.faa -dbtype prot -entry cjeju_FBINDAFG_00440 -out /home/montoliu/40sp/mut_sequences/dnaQ/cjeju.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/cjeju.faa -dbtype prot -entry cjeju_FBINDAFG_01034 -out /home/montoliu/40sp/mut_sequences/mutS/cjeju.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/cjeju.faa -dbtype prot -entry cjeju_FBINDAFG_00574 -out /home/montoliu/40sp/mut_sequences/mutT/cjeju.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/cjeju.faa -dbtype prot -entry cjeju_FBINDAFG_01591 -out /home/montoliu/40sp/mut_sequences/mutY/cjeju.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/cjeju.faa -dbtype prot -entry cjeju_FBINDAFG_01083 -out /home/montoliu/40sp/mut_sequences/uvrD/cjeju.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/cpela.faa -dbtype prot -entry cpela_BLEGILBE_00341 -out /home/montoliu/40sp/mut_sequences/dnaQ/cpela.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/cpela.faa -dbtype prot -entry cpela_BLEGILBE_00114 -out /home/montoliu/40sp/mut_sequences/mutY/cpela.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/cpela.faa -dbtype prot -entry cpela_BLEGILBE_00015 -out /home/montoliu/40sp/mut_sequences/uvrD/cpela.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/csaka.faa -dbtype prot -entry csaka_GEMAJNMG_02368 -out /home/montoliu/40sp/mut_sequences/dnaQ/csaka.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/csaka.faa -dbtype prot -entry csaka_GEMAJNMG_03953 -out /home/montoliu/40sp/mut_sequences/mutH/csaka.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/csaka.faa -dbtype prot -entry csaka_GEMAJNMG_03689 -out /home/montoliu/40sp/mut_sequences/mutL/csaka.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/csaka.faa -dbtype prot -entry csaka_GEMAJNMG_00037 -out /home/montoliu/40sp/mut_sequences/mutS/csaka.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/csaka.faa -dbtype prot -entry csaka_GEMAJNMG_02477 -out /home/montoliu/40sp/mut_sequences/mutT/csaka.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/csaka.faa -dbtype prot -entry csaka_GEMAJNMG_03812 -out /home/montoliu/40sp/mut_sequences/mutY/csaka.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/csaka.faa -dbtype prot -entry csaka_GEMAJNMG_02941 -out /home/montoliu/40sp/mut_sequences/uvrD/csaka.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/ctaiw.faa -dbtype prot -entry ctaiw_AEFJPGKC_01960 -out /home/montoliu/40sp/mut_sequences/dnaQ/ctaiw.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/ctaiw.faa -dbtype prot -entry ctaiw_AEFJPGKC_02502 -out /home/montoliu/40sp/mut_sequences/mutL/ctaiw.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/ctaiw.faa -dbtype prot -entry ctaiw_AEFJPGKC_01155 -out /home/montoliu/40sp/mut_sequences/mutS/ctaiw.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/ctaiw.faa -dbtype prot -entry ctaiw_AEFJPGKC_02670 -out /home/montoliu/40sp/mut_sequences/mutT/ctaiw.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/ctaiw.faa -dbtype prot -entry ctaiw_AEFJPGKC_00319 -out /home/montoliu/40sp/mut_sequences/mutY/ctaiw.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/ctaiw.faa -dbtype prot -entry ctaiw_AEFJPGKC_02207 -out /home/montoliu/40sp/mut_sequences/uvrD/ctaiw.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/ctrac.faa -dbtype prot -entry ctrac_PGDFCPPH_00567 -out /home/montoliu/40sp/mut_sequences/dnaQ/ctrac.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/ctrac.faa -dbtype prot -entry ctrac_PGDFCPPH_00608 -out /home/montoliu/40sp/mut_sequences/mutL/ctrac.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/ctrac.faa -dbtype prot -entry ctrac_PGDFCPPH_00844 -out /home/montoliu/40sp/mut_sequences/mutS/ctrac.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/ctrac.faa -dbtype prot -entry ctrac_PGDFCPPH_00109 -out /home/montoliu/40sp/mut_sequences/mutY/ctrac.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/ctrac.faa -dbtype prot -entry ctrac_PGDFCPPH_00643 -out /home/montoliu/40sp/mut_sequences/uvrD/ctrac.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/cvibr.faa -dbtype prot -entry cvibr_IAJFEHHA_00005 -out /home/montoliu/40sp/mut_sequences/dnaQ/cvibr.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/cvibr.faa -dbtype prot -entry cvibr_IAJFEHHA_00708 -out /home/montoliu/40sp/mut_sequences/mutL/cvibr.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/cvibr.faa -dbtype prot -entry cvibr_IAJFEHHA_00012 -out /home/montoliu/40sp/mut_sequences/mutS/cvibr.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/cvibr.faa -dbtype prot -entry cvibr_IAJFEHHA_00849 -out /home/montoliu/40sp/mut_sequences/mutT/cvibr.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/cvibr.faa -dbtype prot -entry cvibr_IAJFEHHA_00377 -out /home/montoliu/40sp/mut_sequences/mutY/cvibr.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/cvibr.faa -dbtype prot -entry cvibr_IAJFEHHA_01558 -out /home/montoliu/40sp/mut_sequences/uvrD/cvibr.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/eamyl.faa -dbtype prot -entry eamyl_EEMLJACP_00841 -out /home/montoliu/40sp/mut_sequences/dnaQ/eamyl.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/eamyl.faa -dbtype prot -entry eamyl_EEMLJACP_00694 -out /home/montoliu/40sp/mut_sequences/mutH/eamyl.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/eamyl.faa -dbtype prot -entry eamyl_EEMLJACP_00761 -out /home/montoliu/40sp/mut_sequences/mutS/eamyl.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/eamyl.faa -dbtype prot -entry eamyl_EEMLJACP_02695 -out /home/montoliu/40sp/mut_sequences/mutT/eamyl.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/eamyl.faa -dbtype prot -entry eamyl_EEMLJACP_00590 -out /home/montoliu/40sp/mut_sequences/mutY/eamyl.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/eamyl.faa -dbtype prot -entry eamyl_EEMLJACP_00203 -out /home/montoliu/40sp/mut_sequences/uvrD/eamyl.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/ecloa.faa -dbtype prot -entry ecloa_OIAMAHOM_00846 -out /home/montoliu/40sp/mut_sequences/dnaQ/ecloa.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/ecloa.faa -dbtype prot -entry ecloa_OIAMAHOM_03665 -out /home/montoliu/40sp/mut_sequences/mutH/ecloa.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/ecloa.faa -dbtype prot -entry ecloa_OIAMAHOM_00405 -out /home/montoliu/40sp/mut_sequences/mutL/ecloa.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/ecloa.faa -dbtype prot -entry ecloa_OIAMAHOM_03590 -out /home/montoliu/40sp/mut_sequences/mutS/ecloa.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/ecloa.faa -dbtype prot -entry ecloa_OIAMAHOM_00730 -out /home/montoliu/40sp/mut_sequences/mutT/ecloa.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/ecloa.faa -dbtype prot -entry ecloa_OIAMAHOM_03776 -out /home/montoliu/40sp/mut_sequences/mutY/ecloa.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/ecloa.faa -dbtype prot -entry ecloa_OIAMAHOM_04419 -out /home/montoliu/40sp/mut_sequences/uvrD/ecloa.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/ecoli.faa -dbtype prot -entry ecoli_PICPPNBC_00210 -out /home/montoliu/40sp/mut_sequences/dnaQ/ecoli.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/ecoli.faa -dbtype prot -entry ecoli_PICPPNBC_02837 -out /home/montoliu/40sp/mut_sequences/mutH/ecoli.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/ecoli.faa -dbtype prot -entry ecoli_PICPPNBC_04180 -out /home/montoliu/40sp/mut_sequences/mutL/ecoli.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/ecoli.faa -dbtype prot -entry ecoli_PICPPNBC_02738 -out /home/montoliu/40sp/mut_sequences/mutS/ecoli.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/ecoli.faa -dbtype prot -entry ecoli_PICPPNBC_00095 -out /home/montoliu/40sp/mut_sequences/mutT/ecoli.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/ecoli.faa -dbtype prot -entry ecoli_PICPPNBC_02963 -out /home/montoliu/40sp/mut_sequences/mutY/ecoli.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/ecoli.faa -dbtype prot -entry ecoli_PICPPNBC_03814 -out /home/montoliu/40sp/mut_sequences/uvrD/ecoli.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/hinfl.faa -dbtype prot -entry hinfl_EGMADENJ_00143 -out /home/montoliu/40sp/mut_sequences/dnaQ/hinfl.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/hinfl.faa -dbtype prot -entry hinfl_EGMADENJ_00491 -out /home/montoliu/40sp/mut_sequences/mutH/hinfl.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/hinfl.faa -dbtype prot -entry hinfl_EGMADENJ_00014 -out /home/montoliu/40sp/mut_sequences/mutL/hinfl.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/hinfl.faa -dbtype prot -entry hinfl_EGMADENJ_00776 -out /home/montoliu/40sp/mut_sequences/mutS/hinfl.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/hinfl.faa -dbtype prot -entry hinfl_EGMADENJ_01014 -out /home/montoliu/40sp/mut_sequences/mutT/hinfl.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/hinfl.faa -dbtype prot -entry hinfl_EGMADENJ_00867 -out /home/montoliu/40sp/mut_sequences/mutY/hinfl.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/hinfl.faa -dbtype prot -entry hinfl_EGMADENJ_01260 -out /home/montoliu/40sp/mut_sequences/uvrD/hinfl.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/hpylo.faa -dbtype prot -entry hpylo_JMMDLIMG_01142 -out /home/montoliu/40sp/mut_sequences/dnaQ/hpylo.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/hpylo.faa -dbtype prot -entry hpylo_JMMDLIMG_00701 -out /home/montoliu/40sp/mut_sequences/mutS/hpylo.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/hpylo.faa -dbtype prot -entry hpylo_JMMDLIMG_00245 -out /home/montoliu/40sp/mut_sequences/mutY/hpylo.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/hpylo.faa -dbtype prot -entry hpylo_JMMDLIMG_00053 -out /home/montoliu/40sp/mut_sequences/uvrD/hpylo.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/kasco.faa -dbtype prot -entry kasco_CNBFBNNN_03861 -out /home/montoliu/40sp/mut_sequences/dnaQ/kasco.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/kasco.faa -dbtype prot -entry kasco_CNBFBNNN_00924 -out /home/montoliu/40sp/mut_sequences/mutH/kasco.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/kasco.faa -dbtype prot -entry kasco_CNBFBNNN_04310 -out /home/montoliu/40sp/mut_sequences/mutL/kasco.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/kasco.faa -dbtype prot -entry kasco_CNBFBNNN_01022 -out /home/montoliu/40sp/mut_sequences/mutS/kasco.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/kasco.faa -dbtype prot -entry kasco_CNBFBNNN_03978 -out /home/montoliu/40sp/mut_sequences/mutT/kasco.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/kasco.faa -dbtype prot -entry kasco_CNBFBNNN_00785 -out /home/montoliu/40sp/mut_sequences/mutY/kasco.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/kasco.faa -dbtype prot -entry kasco_CNBFBNNN_04607 -out /home/montoliu/40sp/mut_sequences/uvrD/kasco.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/kpneu.faa -dbtype prot -entry kpneu_PFHEFCNI_00948 -out /home/montoliu/40sp/mut_sequences/dnaQ/kpneu.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/kpneu.faa -dbtype prot -entry kpneu_PFHEFCNI_04199 -out /home/montoliu/40sp/mut_sequences/mutH/kpneu.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/kpneu.faa -dbtype prot -entry kpneu_PFHEFCNI_00425 -out /home/montoliu/40sp/mut_sequences/mutL/kpneu.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/kpneu.faa -dbtype prot -entry kpneu_PFHEFCNI_04066 -out /home/montoliu/40sp/mut_sequences/mutS/kpneu.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/kpneu.faa -dbtype prot -entry kpneu_PFHEFCNI_00814 -out /home/montoliu/40sp/mut_sequences/mutT/kpneu.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/kpneu.faa -dbtype prot -entry kpneu_PFHEFCNI_04350 -out /home/montoliu/40sp/mut_sequences/mutY/kpneu.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/kpneu.faa -dbtype prot -entry kpneu_PFHEFCNI_00168 -out /home/montoliu/40sp/mut_sequences/uvrD/kpneu.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/lpneu.faa -dbtype prot -entry lpneu_ICLMNKHK_01397 -out /home/montoliu/40sp/mut_sequences/dnaQ/lpneu.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/lpneu.faa -dbtype prot -entry lpneu_ICLMNKHK_01493 -out /home/montoliu/40sp/mut_sequences/mutH/lpneu.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/lpneu.faa -dbtype prot -entry lpneu_ICLMNKHK_02751 -out /home/montoliu/40sp/mut_sequences/mutL/lpneu.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/lpneu.faa -dbtype prot -entry lpneu_ICLMNKHK_01823 -out /home/montoliu/40sp/mut_sequences/mutS/lpneu.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/lpneu.faa -dbtype prot -entry lpneu_ICLMNKHK_01477 -out /home/montoliu/40sp/mut_sequences/mutT/lpneu.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/lpneu.faa -dbtype prot -entry lpneu_ICLMNKHK_00891 -out /home/montoliu/40sp/mut_sequences/mutY/lpneu.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/lpneu.faa -dbtype prot -entry lpneu_ICLMNKHK_01861 -out /home/montoliu/40sp/mut_sequences/uvrD/lpneu.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/mexto.faa -dbtype prot -entry mexto_GNAGPNAE_01968 -out /home/montoliu/40sp/mut_sequences/dnaQ/mexto.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/mexto.faa -dbtype prot -entry mexto_GNAGPNAE_05002 -out /home/montoliu/40sp/mut_sequences/mutL/mexto.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/mexto.faa -dbtype prot -entry mexto_GNAGPNAE_05019 -out /home/montoliu/40sp/mut_sequences/mutS/mexto.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/mexto.faa -dbtype prot -entry mexto_GNAGPNAE_00181 -out /home/montoliu/40sp/mut_sequences/mutT/mexto.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/mexto.faa -dbtype prot -entry mexto_GNAGPNAE_03745 -out /home/montoliu/40sp/mut_sequences/mutY/mexto.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/mexto.faa -dbtype prot -entry mexto_GNAGPNAE_00192 -out /home/montoliu/40sp/mut_sequences/uvrD/mexto.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/neuro.faa -dbtype prot -entry neuro_LDFBOEFA_00152 -out /home/montoliu/40sp/mut_sequences/dnaQ/neuro.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/neuro.faa -dbtype prot -entry neuro_LDFBOEFA_01825 -out /home/montoliu/40sp/mut_sequences/mutL/neuro.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/neuro.faa -dbtype prot -entry neuro_LDFBOEFA_01787 -out /home/montoliu/40sp/mut_sequences/mutS/neuro.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/neuro.faa -dbtype prot -entry neuro_LDFBOEFA_02328 -out /home/montoliu/40sp/mut_sequences/mutT/neuro.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/neuro.faa -dbtype prot -entry neuro_LDFBOEFA_00065 -out /home/montoliu/40sp/mut_sequences/mutY/neuro.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/neuro.faa -dbtype prot -entry neuro_LDFBOEFA_01555 -out /home/montoliu/40sp/mut_sequences/uvrD/neuro.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/nmeni.faa -dbtype prot -entry nmeni_ALPHLGIA_01985 -out /home/montoliu/40sp/mut_sequences/dnaQ/nmeni.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/nmeni.faa -dbtype prot -entry nmeni_ALPHLGIA_02047 -out /home/montoliu/40sp/mut_sequences/mutL/nmeni.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/nmeni.faa -dbtype prot -entry nmeni_ALPHLGIA_01228 -out /home/montoliu/40sp/mut_sequences/mutS/nmeni.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/nmeni.faa -dbtype prot -entry nmeni_ALPHLGIA_01668 -out /home/montoliu/40sp/mut_sequences/mutT/nmeni.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/nmeni.faa -dbtype prot -entry nmeni_ALPHLGIA_02091 -out /home/montoliu/40sp/mut_sequences/mutY/nmeni.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/nmeni.faa -dbtype prot -entry nmeni_ALPHLGIA_01448 -out /home/montoliu/40sp/mut_sequences/uvrD/nmeni.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/paeru.faa -dbtype prot -entry paeru_BOBHOCID_01871 -out /home/montoliu/40sp/mut_sequences/dnaQ/paeru.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/paeru.faa -dbtype prot -entry paeru_BOBHOCID_05118 -out /home/montoliu/40sp/mut_sequences/mutL/paeru.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/paeru.faa -dbtype prot -entry paeru_BOBHOCID_03744 -out /home/montoliu/40sp/mut_sequences/mutS/paeru.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/paeru.faa -dbtype prot -entry paeru_BOBHOCID_04545 -out /home/montoliu/40sp/mut_sequences/mutT/paeru.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/paeru.faa -dbtype prot -entry paeru_BOBHOCID_05322 -out /home/montoliu/40sp/mut_sequences/mutY/paeru.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/paeru.faa -dbtype prot -entry paeru_BOBHOCID_05631 -out /home/montoliu/40sp/mut_sequences/uvrD/paeru.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/pcaro.faa -dbtype prot -entry pcaro_BDEOPBEG_01095 -out /home/montoliu/40sp/mut_sequences/dnaQ/pcaro.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/pcaro.faa -dbtype prot -entry pcaro_BDEOPBEG_03340 -out /home/montoliu/40sp/mut_sequences/mutH/pcaro.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/pcaro.faa -dbtype prot -entry pcaro_BDEOPBEG_00517 -out /home/montoliu/40sp/mut_sequences/mutL/pcaro.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/pcaro.faa -dbtype prot -entry pcaro_BDEOPBEG_03265 -out /home/montoliu/40sp/mut_sequences/mutS/pcaro.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/pcaro.faa -dbtype prot -entry pcaro_BDEOPBEG_00644 -out /home/montoliu/40sp/mut_sequences/mutT/pcaro.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/pcaro.faa -dbtype prot -entry pcaro_BDEOPBEG_03347 -out /home/montoliu/40sp/mut_sequences/mutY/pcaro.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/pcaro.faa -dbtype prot -entry pcaro_BDEOPBEG_00272 -out /home/montoliu/40sp/mut_sequences/uvrD/pcaro.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/pmira.faa -dbtype prot -entry pmira_OBIAMHEN_00219 -out /home/montoliu/40sp/mut_sequences/dnaQ/pmira.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/pmira.faa -dbtype prot -entry pmira_OBIAMHEN_02093 -out /home/montoliu/40sp/mut_sequences/mutH/pmira.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/pmira.faa -dbtype prot -entry pmira_OBIAMHEN_03386 -out /home/montoliu/40sp/mut_sequences/mutL/pmira.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/pmira.faa -dbtype prot -entry pmira_OBIAMHEN_02238 -out /home/montoliu/40sp/mut_sequences/mutS/pmira.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/pmira.faa -dbtype prot -entry pmira_OBIAMHEN_02060 -out /home/montoliu/40sp/mut_sequences/mutT/pmira.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/pmira.faa -dbtype prot -entry pmira_OBIAMHEN_00313 -out /home/montoliu/40sp/mut_sequences/mutY/pmira.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/pmira.faa -dbtype prot -entry pmira_OBIAMHEN_03361 -out /home/montoliu/40sp/mut_sequences/uvrD/pmira.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/pmult.faa -dbtype prot -entry pmult_OEOFEKNE_01417 -out /home/montoliu/40sp/mut_sequences/dnaQ/pmult.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/pmult.faa -dbtype prot -entry pmult_OEOFEKNE_00336 -out /home/montoliu/40sp/mut_sequences/mutH/pmult.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/pmult.faa -dbtype prot -entry pmult_OEOFEKNE_01631 -out /home/montoliu/40sp/mut_sequences/mutL/pmult.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/pmult.faa -dbtype prot -entry pmult_OEOFEKNE_01132 -out /home/montoliu/40sp/mut_sequences/mutS/pmult.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/pmult.faa -dbtype prot -entry pmult_OEOFEKNE_00488 -out /home/montoliu/40sp/mut_sequences/mutT/pmult.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/pmult.faa -dbtype prot -entry pmult_OEOFEKNE_00677 -out /home/montoliu/40sp/mut_sequences/mutY/pmult.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/pmult.faa -dbtype prot -entry pmult_OEOFEKNE_00049 -out /home/montoliu/40sp/mut_sequences/uvrD/pmult.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/rlegu.faa -dbtype prot -entry rlegu_LBPNNKIN_06878 -out /home/montoliu/40sp/mut_sequences/dnaQ/rlegu.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/rlegu.faa -dbtype prot -entry rlegu_LBPNNKIN_03067 -out /home/montoliu/40sp/mut_sequences/mutL/rlegu.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/rlegu.faa -dbtype prot -entry rlegu_LBPNNKIN_02558 -out /home/montoliu/40sp/mut_sequences/mutS/rlegu.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/rlegu.faa -dbtype prot -entry rlegu_LBPNNKIN_06420 -out /home/montoliu/40sp/mut_sequences/mutT/rlegu.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/rlegu.faa -dbtype prot -entry rlegu_LBPNNKIN_03250 -out /home/montoliu/40sp/mut_sequences/mutY/rlegu.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/rlegu.faa -dbtype prot -entry rlegu_LBPNNKIN_05411 -out /home/montoliu/40sp/mut_sequences/uvrD/rlegu.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/rsola.faa -dbtype prot -entry rsola_OKPONLKL_00475 -out /home/montoliu/40sp/mut_sequences/dnaQ/rsola.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/rsola.faa -dbtype prot -entry rsola_OKPONLKL_01065 -out /home/montoliu/40sp/mut_sequences/mutL/rsola.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/rsola.faa -dbtype prot -entry rsola_OKPONLKL_03040 -out /home/montoliu/40sp/mut_sequences/mutS/rsola.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/rsola.faa -dbtype prot -entry rsola_OKPONLKL_01264 -out /home/montoliu/40sp/mut_sequences/mutT/rsola.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/rsola.faa -dbtype prot -entry rsola_OKPONLKL_02271 -out /home/montoliu/40sp/mut_sequences/mutY/rsola.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/rsola.faa -dbtype prot -entry rsola_OKPONLKL_00771 -out /home/montoliu/40sp/mut_sequences/uvrD/rsola.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/sdyse.faa -dbtype prot -entry sdyse_LMDHAIMA_00775 -out /home/montoliu/40sp/mut_sequences/dnaQ/sdyse.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/sdyse.faa -dbtype prot -entry sdyse_LMDHAIMA_03531 -out /home/montoliu/40sp/mut_sequences/mutH/sdyse.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/sdyse.faa -dbtype prot -entry sdyse_LMDHAIMA_00362 -out /home/montoliu/40sp/mut_sequences/mutL/sdyse.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/sdyse.faa -dbtype prot -entry sdyse_LMDHAIMA_03431 -out /home/montoliu/40sp/mut_sequences/mutS/sdyse.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/sdyse.faa -dbtype prot -entry sdyse_LMDHAIMA_00661 -out /home/montoliu/40sp/mut_sequences/mutT/sdyse.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/sdyse.faa -dbtype prot -entry sdyse_LMDHAIMA_03680 -out /home/montoliu/40sp/mut_sequences/mutY/sdyse.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/sdyse.faa -dbtype prot -entry sdyse_LMDHAIMA_04650 -out /home/montoliu/40sp/mut_sequences/uvrD/sdyse.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/sente.faa -dbtype prot -entry sente_EBBPGFGJ_00262 -out /home/montoliu/40sp/mut_sequences/dnaQ/sente.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/sente.faa -dbtype prot -entry sente_EBBPGFGJ_03021 -out /home/montoliu/40sp/mut_sequences/mutH/sente.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/sente.faa -dbtype prot -entry sente_EBBPGFGJ_04373 -out /home/montoliu/40sp/mut_sequences/mutL/sente.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/sente.faa -dbtype prot -entry sente_EBBPGFGJ_02924 -out /home/montoliu/40sp/mut_sequences/mutS/sente.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/sente.faa -dbtype prot -entry sente_EBBPGFGJ_00134 -out /home/montoliu/40sp/mut_sequences/mutT/sente.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/sente.faa -dbtype prot -entry sente_EBBPGFGJ_03127 -out /home/montoliu/40sp/mut_sequences/mutY/sente.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/sente.faa -dbtype prot -entry sente_EBBPGFGJ_03972 -out /home/montoliu/40sp/mut_sequences/uvrD/sente.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/smalt.faa -dbtype prot -entry smalt_APOOPAAO_00946 -out /home/montoliu/40sp/mut_sequences/dnaQ/smalt.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/smalt.faa -dbtype prot -entry smalt_APOOPAAO_03232 -out /home/montoliu/40sp/mut_sequences/mutL/smalt.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/smalt.faa -dbtype prot -entry smalt_APOOPAAO_01415 -out /home/montoliu/40sp/mut_sequences/mutS/smalt.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/smalt.faa -dbtype prot -entry smalt_APOOPAAO_00709 -out /home/montoliu/40sp/mut_sequences/mutT/smalt.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/smalt.faa -dbtype prot -entry smalt_APOOPAAO_01947 -out /home/montoliu/40sp/mut_sequences/mutY/smalt.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/smalt.faa -dbtype prot -entry smalt_APOOPAAO_04549 -out /home/montoliu/40sp/mut_sequences/uvrD/smalt.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/smarc.faa -dbtype prot -entry smarc_FFJMIMPG_00802 -out /home/montoliu/40sp/mut_sequences/dnaQ/smarc.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/smarc.faa -dbtype prot -entry smarc_FFJMIMPG_03826 -out /home/montoliu/40sp/mut_sequences/mutH/smarc.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/smarc.faa -dbtype prot -entry smarc_FFJMIMPG_00342 -out /home/montoliu/40sp/mut_sequences/mutL/smarc.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/smarc.faa -dbtype prot -entry smarc_FFJMIMPG_00745 -out /home/montoliu/40sp/mut_sequences/mutS/smarc.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/smarc.faa -dbtype prot -entry smarc_FFJMIMPG_00689 -out /home/montoliu/40sp/mut_sequences/mutT/smarc.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/smarc.faa -dbtype prot -entry smarc_FFJMIMPG_04026 -out /home/montoliu/40sp/mut_sequences/mutY/smarc.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/smarc.faa -dbtype prot -entry smarc_FFJMIMPG_00153 -out /home/montoliu/40sp/mut_sequences/uvrD/smarc.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/sonei.faa -dbtype prot -entry sonei_NDNGDDGP_02433 -out /home/montoliu/40sp/mut_sequences/dnaQ/sonei.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/sonei.faa -dbtype prot -entry sonei_NDNGDDGP_01281 -out /home/montoliu/40sp/mut_sequences/mutH/sonei.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/sonei.faa -dbtype prot -entry sonei_NDNGDDGP_00586 -out /home/montoliu/40sp/mut_sequences/mutL/sonei.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/sonei.faa -dbtype prot -entry sonei_NDNGDDGP_03307 -out /home/montoliu/40sp/mut_sequences/mutS/sonei.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/sonei.faa -dbtype prot -entry sonei_NDNGDDGP_00404 -out /home/montoliu/40sp/mut_sequences/mutT/sonei.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/sonei.faa -dbtype prot -entry sonei_NDNGDDGP_03240 -out /home/montoliu/40sp/mut_sequences/mutY/sonei.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/sonei.faa -dbtype prot -entry sonei_NDNGDDGP_00453 -out /home/montoliu/40sp/mut_sequences/uvrD/sonei.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/vchol.faa -dbtype prot -entry vchol_JOBCAADD_00590 -out /home/montoliu/40sp/mut_sequences/dnaQ/vchol.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/vchol.faa -dbtype prot -entry vchol_JOBCAADD_02045 -out /home/montoliu/40sp/mut_sequences/mutH/vchol.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/vchol.faa -dbtype prot -entry vchol_JOBCAADD_02385 -out /home/montoliu/40sp/mut_sequences/mutL/vchol.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/vchol.faa -dbtype prot -entry vchol_JOBCAADD_02180 -out /home/montoliu/40sp/mut_sequences/mutS/vchol.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/vchol.faa -dbtype prot -entry vchol_JOBCAADD_00449 -out /home/montoliu/40sp/mut_sequences/mutT/vchol.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/vchol.faa -dbtype prot -entry vchol_JOBCAADD_02253 -out /home/montoliu/40sp/mut_sequences/mutY/vchol.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/vchol.faa -dbtype prot -entry vchol_JOBCAADD_02576 -out /home/montoliu/40sp/mut_sequences/uvrD/vchol.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/xfast.faa -dbtype prot -entry xfast_GBDFHHAF_01413 -out /home/montoliu/40sp/mut_sequences/dnaQ/xfast.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/xfast.faa -dbtype prot -entry xfast_GBDFHHAF_02221 -out /home/montoliu/40sp/mut_sequences/mutL/xfast.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/xfast.faa -dbtype prot -entry xfast_GBDFHHAF_01259 -out /home/montoliu/40sp/mut_sequences/mutS/xfast.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/xfast.faa -dbtype prot -entry xfast_GBDFHHAF_00459 -out /home/montoliu/40sp/mut_sequences/mutT/xfast.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/xfast.faa -dbtype prot -entry xfast_GBDFHHAF_01055 -out /home/montoliu/40sp/mut_sequences/mutY/xfast.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/xfast.faa -dbtype prot -entry xfast_GBDFHHAF_00039 -out /home/montoliu/40sp/mut_sequences/uvrD/xfast.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/ypest.faa -dbtype prot -entry ypest_GCILODAP_04016 -out /home/montoliu/40sp/mut_sequences/dnaQ/ypest.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/ypest.faa -dbtype prot -entry ypest_GCILODAP_00206 -out /home/montoliu/40sp/mut_sequences/mutH/ypest.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/ypest.faa -dbtype prot -entry ypest_GCILODAP_00621 -out /home/montoliu/40sp/mut_sequences/mutL/ypest.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/ypest.faa -dbtype prot -entry ypest_GCILODAP_01795 -out /home/montoliu/40sp/mut_sequences/mutS/ypest.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/ypest.faa -dbtype prot -entry ypest_GCILODAP_00428 -out /home/montoliu/40sp/mut_sequences/mutT/ypest.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/ypest.faa -dbtype prot -entry ypest_GCILODAP_00043 -out /home/montoliu/40sp/mut_sequences/mutY/ypest.fasta
blastdbcmd -db /home/montoliu/40sp/data_renamed/ypest.faa -dbtype prot -entry ypest_GCILODAP_01290 -out /home/montoliu/40sp/mut_sequences/uvrD/ypest.fasta
